exports.All_PERMISSIONS = [
  "WRITE_MEETING",
  "WRITE_FEATURE",
  "HOST_MEETING",
  "MANAGE_MEETING",
  "WRITE_USER",
  "WRITE_ROLE",
  "READ_USER",
];

exports.permissionsConstant = {
  WRITE_MEETING: "WRITE_MEETING",
  WRITE_FEATURE: "WRITE_FEATURE",
  HOST_MEETING: "HOST_MEETING",
  MANAGE_MEETING: "MANAGE_MEETING",
  WRITE_USER: "WRITE_USER",
  WRITE_ROLE: "WRITE_ROLE",
  READ_USER: "READ_USER",
};
